### ISSUE TITLE
Suggestion ( Greenery 4.0 and above )

### ISSUE THREAD

**Issue by Kasia1403** [juraj-hrivnak/Greenery#11]
To change dependency from Forgelin Continuous to Forgelin like in older versions.

**Comment by juraj-hrivnak** [comment]
No, why do you want that?

**Comment by juraj-hrivnak** [comment]
It is not technically possible. 
Forgelin uses outdated Kotlin, and Forgelin Continuous is just an updated version of Forgelin.

**Comment by Kasia1403** [comment]
I wanted it to work with FutureMC, but FutureMC wants Forgelin, not Forgelin Continuous.

**Comment by juraj-hrivnak** [comment]
You can't use both?

**Comment by Kasia1403** [comment]
> You can't use both?

No, because Minecraft says that I have duplicated mods.

**Comment by juraj-hrivnak** [comment]
Try to use this version of Forgelin-Continuous: [Forgelin-Continuous-1.8.20.1.jar.zip](https://github.com/juraj-hrivnak/Greenery/files/11412936/Forgelin-Continuous-1.8.20.1.jar.zip)
