### ISSUE TITLE
Direct No Tree Punching compatibility 

### ISSUE THREAD

**Issue by Lonelyxiya** [juraj-hrivnak/Greenery#14]
https://github.com/alcatrazEscapee/no-tree-punching

**Comment by Lonelyxiya** [comment]
Playing any Greenery module's grass will not drop plant fiber, it needs to be compatible.

**Comment by juraj-hrivnak** [comment]
Greenery grasses drop the default loot for vanilla grass. So this is an issue from No Tree Punching.
