### ISSUE TITLE
Seagrass duplication bug

### ISSUE THREAD

**Issue by Mindr0ide** [juraj-hrivnak/Greenery#15]
When you right-click on Greenery's seagrass with a seagrass item in your main hand, the seagrass will emit breaking particles but remain, and it will also drop a new duped seagrass. (maintening right click will basically generate infinite amount of seagrass). This bug also work in survival mode.

**Comment by Mindr0ide** [comment]
mod version where I found the bug: Greenery-1.12.2-4.3

**Comment by juraj-hrivnak** [comment]
What's your version of Fluidlogged API?

**Comment by Mindr0ide** [comment]
it's Fluidlogged-API-v2.2.4-mc1.12.2.jar

**Comment by juraj-hrivnak** [comment]
Could you try it with the latest version on Modrinth?
https://modrinth.com/mod/fluidlogged-api/versions#all-versions

**Comment by juraj-hrivnak** [comment]
Okay, thanks for the report

**Comment by juraj-hrivnak** [comment]
I can not reproduce it only with Greenery installed. Do you have any other mods installed?
I presume it is an issue with some "right-click to harvest" mod.

**Comment by Mindr0ide** [comment]
Actually yes is it, because  I tested with only greenery loaded and there wasn't the bug, but it showed up with Quark:RotN Edition, with the "right-click to harvest" module on.

**Comment by Mindr0ide** [comment]
here is the mod list that I have used to reproduce the bug
![image](https://github.com/juraj-hrivnak/Greenery/assets/142521261/a3f52e18-605d-4501-a7ac-3e2a1fb545f5)

**Comment by Mindr0ide** [comment]
and when the "right-click to harvest" module from Quark is set to off, the bug doesn't appear

**Comment by juraj-hrivnak** [comment]
Okay, thanks. I will try to fix it, somehow.

**Comment by juraj-hrivnak** [comment]
@Mindr0ide can you test if this is still present in [v4.4](https://legacy.curseforge.com/minecraft/mc-mods/greenery/files/4767522)?

**Comment by juraj-hrivnak** [comment]
Fixed in v4.4
