### ISSUE TITLE
the forgelin continuous issue

### ISSUE THREAD

**Issue by Biviho** [juraj-hrivnak/Greenery#16]
hi, i opened this issue cause i've tried using the new update of greenery and i saw it require forgelin continuous...
since that mod is not a substitution, but a new mod incompatible with the previous forgelin, it make greenery incompatible with basically all mods that uses the old forgelin.

did forgelin continuous have some needed functionality that the old forgelin does not have?

**Comment by juraj-hrivnak** [comment]
You use old version of forgelin continuous, probably.

**Comment by Biviho** [comment]
Well, yeah, sort of: i use shadofact's forgeling, the thing is that forgelin continuous is incompatible with shadowfact forgelin, and it isn't an update to the old one, it's a totally different mod, so:

- if i try to use greenery, i have to also use forgelin continuous
- if i use forgelin continuous i cant have shadowfact's forgelin
- if i don't have shadowfact's forgelin i can't use the various mods that need shadowfact forgelin
- => greenery is incompatible with all the mods that use shadowfact's forgelin

**Comment by juraj-hrivnak** [comment]
Send me the `latest.log` and mod versions.
What you are saying is not true. Shadowfact's forgelin and Forgelin Continuous are compatible with each other.

**Comment by Biviho** [comment]
so, i guess they are, i've tried to reproduce the crash on startup i had, but i wasn't able to, instead the game started as normal...have no idea what happened then
