### ISSUE TITLE
The ability to configure custom plant placement

### ISSUE THREAD

**Issue by Turkey9002** [juraj-hrivnak/Greenery#17]
Been loving this mod so far but is it possible to configure the way the plant is placed? I'd like to make a custom seagrass but I prefer it to stay still on the same spot each time I place it like vanilla's seagrass. Greenery's custom plants get placed on random spots like flowers.

**Comment by juraj-hrivnak** [comment]
Do you mean with bonemeal?

**Comment by Turkey9002** [comment]
Here's a comparison between Subaquatic's Seagrass and Greenery's Watermilfoil. The placement is more random on the right and I was wanting to make it more like Subaquatic on the left.
![seagrass1](https://github.com/juraj-hrivnak/Greenery/assets/86805568/9f1b90ef-4b40-4558-afe9-e0509246babb)

**Comment by Foreck1** [comment]
While agree with the ability to change it for maximum customization; wouldn't it actually look better if Subaquatic added the ability for block offset to make plants look more organic?

**Comment by juraj-hrivnak** [comment]
Ah, this. I can easily add a configuration for that.

**Comment by juraj-hrivnak** [comment]
In `v4.6`, add `"hasOffset": false` to the submerged plant `.json` configs to disable and then run `/greenery reload`.
The blocks must be updated to take effect, though.

**Comment by Turkey9002** [comment]
Wonderful! Thank you for the swift response!
