### ISSUE TITLE
Mod foliage integrations

### ISSUE THREAD

**Issue by LUEZISS** [juraj-hrivnak/Greenery#21]
Please make the foliage fitting the pink hue of cotton candy grass in CottonCandyPlains biome featured in the Candy World mod. You can also take a look on other biomes from this mod, not sure how they look tho, cuz they are pretty rare.

P.S. Also some foliage for Crystal Forest biome from Plants mod would be great as well.

**Comment by juraj-hrivnak** [comment]
This issue on their side. Greenery plants respect the grass tint. You can change the texture, or add your own plants using the config.

**Comment by LUEZISS** [comment]
Does adding this biome to the dictionary list, then inverting the order, will results in blacklisting it?

**Comment by juraj-hrivnak** [comment]
I’m not sure what you mean

**Comment by LUEZISS** [comment]
In the world gen config file there is a place where you can put biome names, where certain foliage is supposed to spawn. In the line below there is an invert option (false by default). Does adding `COTTONCANDYPLAINS` to it, then setting the option below as true will result in spawning grass in every biome BESIDE the following one typed above?

**Comment by juraj-hrivnak** [comment]
Yes, `!` mean everywhere except the biome/biome dictionary

**Comment by LUEZISS** [comment]
Ok, that's all I want to know. Thanks for the quick reply.

**Comment by juraj-hrivnak** [comment]
Ok, I am closing this then :)
