### ISSUE TITLE
Crash with newest version ( 2.5 )

### ISSUE THREAD

**Issue by Kasia1403** [juraj-hrivnak/Greenery#8]
[crash-2023-01-17_11.17.43-client.txt](https://github.com/juraj-hrivnak/Greenery/files/10433855/crash-2023-01-17_11.17.43-client.txt)

**Comment by juraj-hrivnak** [comment]
Probably a compilation error.

**Comment by Kasia1403** [comment]
@juraj-hrivnak  Could You fix this error ?

**Comment by juraj-hrivnak** [comment]
Of course. Be patient!

**Comment by Kasia1403** [comment]
OK.

**Comment by juraj-hrivnak** [comment]
Fixed in v2.6
